# Generated by Django 6.0.4 on 2026-04-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
